// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7BFAFfxfX6EN_DesmByJtDm3j7apSyA',
    appId: '1:195170938530:web:990e960dbd9c9ff9d3f1fb',
    messagingSenderId: '195170938530',
    projectId: 'messanger-live-64ab7',
    authDomain: 'messanger-live-64ab7.firebaseapp.com',
    storageBucket: 'messanger-live-64ab7.appspot.com',
    measurementId: 'G-5WGRY1TF92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAddKLLmUkC5SPjgMbqDQSeHDamfTyTF28',
    appId: '1:195170938530:android:1740df6197b9e542d3f1fb',
    messagingSenderId: '195170938530',
    projectId: 'messanger-live-64ab7',
    storageBucket: 'messanger-live-64ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4CWzqmXHjU89aJnnyOFZk6kDXFXNyQ4g',
    appId: '1:195170938530:ios:3871d4ee9741c14ad3f1fb',
    messagingSenderId: '195170938530',
    projectId: 'messanger-live-64ab7',
    storageBucket: 'messanger-live-64ab7.appspot.com',
    iosClientId: '195170938530-khd7dujh4dull38cmlnu9absmntq4s5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4CWzqmXHjU89aJnnyOFZk6kDXFXNyQ4g',
    appId: '1:195170938530:ios:6a6a5980fe8b05d4d3f1fb',
    messagingSenderId: '195170938530',
    projectId: 'messanger-live-64ab7',
    storageBucket: 'messanger-live-64ab7.appspot.com',
    iosClientId: '195170938530-k0qq04jo6kcqn62pccjosgpd32rk3m9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageLive.RunnerTests',
  );
}
